# Generated by Django 2.0.5 on 2018-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='article_topic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='oa_status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='oa_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
